name: 更新最近活动

on:
  schedule:
    - cron: '0 0 * * *' # 每天午夜UTC时间执行一次
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: 更新此仓库README中的最近活动
    permissions:
      contents: write  # 推送更改所需的权限

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # 获取完整历史记录以便更好地进行git操作
      
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'chore: 更新最近活动 [skip ci]'
          MAX_LINES: 5
          GH_USERNAME: wu9o
          COMMIT_NAME: github-actions[bot]
          COMMIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          TARGET_FILE: README.md
          EMPTY_COMMIT_MSG: ':memo: 空提交以在60天无活动后保持工作流活跃'
